const genres = [
    'Action/Adventure',
    'Animals',
    'Animation',
    'Biography',
    'Comedy',
    'Cooking',
    'Dance',
    'Documentary',
    'Drama',
    'Education',
    'Entertainment',
    'Family',
    'Fantasy',
    'History',
    'Horror',
    'Independent',
    'International',
    'Kids',
    'Kids & Family',
    'Medical',
    'Military/War',
    'Music',
    'Musical',
    'Mystery/Crime',
    'Nature',
    'Paranormal',
    'Politics',
    'Racing',
    'Romance',
    'Sci-Fi/Horror',
    'Science',
    'Science Fiction',
    'Science/Nature',
    'Spanish',
    'Travel',
    'Western'
]

module.exports = genres