export const LOAD = {
    LOADING: 'LOADING',
    SUCCESS: 'LOAD_SUCCESS',
    FAIL: 'LOAD_FAIL'
}

export const ERROR = {
    SET_ERROR: 'SET_ERROR',
    CLEAR_ERROR: 'CLEAR_ERROR'
}

// main
export const SWIPE_ITEMS = {
    LOAD_ITEMS: 'SWIPE_LOAD_ITEMS',
    SET_ITEMS: 'SWIPE_SET_ITEMS',
    CLEAR_ITEMS: 'SWIPE_CLEAR_ITEMS'
}

export const MAIN_ITEMS = {
    LOAD_ITEMS: 'MAIN_LOAD_ITEMS',
    SET_ITEMS: 'MAIN_SET_ITEMS',
    CLEAR_ITEMS: 'MAIN_CLEAR_ITEMS'
}

export const MAIN_MOVIES = {
    LOAD_ITEMS: 'MAIN_LOAD_MOVIES',
    SET_ITEMS: 'MAIN_SET_MOVIES',
    CLEAR_ITEMS: 'MAIN_CLEAR_MOVIES'
}

export const MAIN_TVSERIES = {
    LOAD_ITEMS: 'MAIN_LOAD_TVSERIES',
    SET_ITEMS: 'MAIN_SET_TVSERIES',
    CLEAR_ITEMS: 'MAIN_CLEAR_TVSERIES'
}

export const MAIN_ITEM = {
    LOAD_ITEM: 'MAIN_LOAD_ITEM',
    SET_ITEM: 'MAIN_SET_ITEM',
    CLEAR_ITEM: 'MAIN_CLEAR_ITEM'
}

export const EXPECTED_ITEMS = {
    LOAD_ITEMS: 'EXPECTED_LOAD_ITEMS',
    SET_ITEMS: 'EXPECTED_SET_ITEMS',
    CLEAR_ITEMS: 'EXPECTED_CLEAR_ITEMS'
}

export const MAIN_PARAMS = {
    CHANGE_PARAM: 'MAIN_CHANGE_PARAM',
    SET_DEFAULT: 'MAIN_SET_DEFAULT'
}

export const GRID_ITEMS = {
    LOAD_ITEMS: 'GRID_LOAD_ITEMS',
    SET_ITEMS: 'GRID_SET_ITEMS',
    CLEAR_ITEMS: 'GRID_CLEAR_ITEMS'
}

export const LIST_ITEMS = {
    LOAD_ITEMS: 'LIST_LOAD_ITEMS',
    SET_ITEMS: 'LIST_SET_ITEMS',
    CLEAR_ITEMS: 'LIST_CLEAR_ITEMS'
}
// -----------------------

// admin
export const ADMIN_ITEMS = {
    SET_ITEMS: 'ADMIN_SET_ITEMS',
    CHANGE_ITEM_BY: 'ADMIN_CHANGE_ITEM_BY',
    CHANGE_ITEM: 'ADMIN_CHANGE_ITEM',
    DELETE_ITEM: 'ADMIN_DELETE_ITEM'
}

export const ADMIN_ITEM = {
    LOAD_ITEM: 'ADMIN_LOAD_ITEM_ONE',
    DELETE_KEY: 'ADMIN_DELETE_KEY_ITEM_ONE',
    SET_ITEM: 'ADMIN_SET_ITEM_ONE',
    CHANGE_ITEM: 'ADMIN_CHANGE_ITEM_ONE',
    CLEAR_ITEM: 'ADMIN_CLEAR_ITEM_ONE',
    SEND_ITEM: 'ADMIN_SEND_ITEM_ONE'
}

export const ADMIN_ITEM_STATUS = {
    LOAD: 'ADMIN_ITEM_STATUS_LOAD',
    LOAD_SUCCESS: 'ADMIN_ITEM_STATUS_SUCCESS',
    LOAD_FAIL: 'ADMIN_ITEM_STATUS_FAIL',
    CLEAR_STATUS: 'ADMIN_CLEAR_STATUS'
}

export const ADMIN_ITEM_DELETE = {
    LOAD: 'ADMIN_ITEM_DELETE_LOAD',
    LOAD_SUCCESS: 'ADMIN_ITEM_DELETE_SUCCESS',
    LOAD_FAIL: 'ADMIN_ITEM_DELETE_SUCCESS',
    CLEAR_DELETE: 'ADMIN_CLEAR_DELETE'
}
// -----------------------