import { useState, useEffect } from 'react'

export const outsideCustomStyles = {
    container: () => ({
        width: '100%',
        position: 'relative',
        // fontWeight: '400',
        border: 'none',
        height: '50px',
        color: '#fff',
        padding: '0 20px',
        letterSpacing: '0.2px',
        backgroundColor: '#2b2b31',
        marginBottom: '20px',
        fontFamily: '\'Open Sans\', sans-serif',
        fontSize: '15px',
    }),
    control: () => ({
        // none of react-select's styles are passed to <Control />
        width: '100%',
        height: '100%',
        padding: 0,
        margin: 0,
        display: 'flex',
        justifyContent: 'space-between',
        backgroundColor: '#2b2b31'
    }),
    valueContainer: () => ({
        padding: 0,
        margin: 0,
        display: 'flex',
        color: '#fff',
        alignItems: 'center',
    }),
    input: () => ({
        color: '#fff'
    }),
    multiValue: () => ({
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
        color: '#fff',
        border: 'none',
        borderRadius: '0',
        height: '30px',
        display: 'flex',
        flexDirection: 'row-reverse',
        justifyContent: 'flex-start',
        alignItems: 'center',
        padding: '0 10px',
        margin: '0 5px'
    }),
    multiValueLabel: () => ({
        color: '#fff',
    }),
    multiValueRemove: () => ({
        color: '#ff55a5',
    }),
    placeholder: () => ({
        color: '#999',
    }),
    dropdownIndicator: () => ({
        display: 'none'
    }),
    indicatorSeparator: () => ({
        display: 'none'
    }),
    clearIndicator: () => ({
        display: 'none'
    }),
    menu: () => ({
        backgroundColor: '#2b2b31',
        width: '100%',
        height: '230px',
        overflow: 'hidden',
        position: 'absolute',
        top: '100%',
        left: 0,
        zIndex: 5,
        padding: '15px 0',
        boxShadow: '0 5px 25px 0 rgba(0,0,0,0.3)',

        ':before': {
            content: '" "',
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '2px',
            display: 'block',
            zIndex: 6,
            background: 'linear-gradient(90deg, #ff55a5 0%, #ff5860 100%)',
            boxShadow: '0 0 20px 0 rgba(255,88,96,0.5)',
        }
    }),
    menuList: () => ({
        height: '100%',
        overflowY: 'scroll'
    }),
    option: (styles, nimadir) => ({
        cursor: 'pointer',
        padding: '0 20px',
        lineHeight: '40px',
        fontSize: '16px',
        fontWeight: '300',
        display: 'block',
        color: '#bbb',

        ':hover': {
            ...styles[':hover'],
            color: '#ff55a5'
        }
    }),
}

function getWindowDimensions() {
    const { innerWidth: width, innerHeight: height } = window
    return {
        width,
        height
    }
}

export default function useWindowDimensions() {
    const [windowDimensions, setWindowDimensions] = useState(getWindowDimensions())

    useEffect(() => {
        function handleResize() {
            setWindowDimensions(getWindowDimensions())
        }

        window.addEventListener('resize', handleResize)
        return () => window.removeEventListener('resize', handleResize)
    }, []);

    return windowDimensions
}

export const qualities = [
    'FullHD',
    'HD',
    'mp4',
    '3gp'
]

export const genres = [
    'Action',
    'Animation',
    'Comedy',
    'Crime',
    'Drama',
    'Fantasy',
    'Historical',
    'Horror',
    'Romance',
    'Science-fiction',
    'Thriller',
    'Western',
    'Otheer',
]

export const countries = [
    'Afghanistan',
    'Åland Islands',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Bouvet Island',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo',
    'Cook Islands',
    'Costa Rica',
    'Cote D\'ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Greenland',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea',
    'Kuwait',
    'Kyrgyzstan',
    'Lao People\'s Democratic Republic',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libyan Arab Jamahiriya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'Netherlands Antilles',
    'New Caledonia',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'Norfolk Island',
    'Northern Mariana Islands',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Pitcairn',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Reunion',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syrian Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-leste',
    'Togo',
    'Tokelau',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks and Caicos Islands',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Viet Nam',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
]